Решена Задача 1-2 #5
MarinaPaley/Informatics-TS pull request #10
Opened 2021-04-06 17:31 UTC by MarinaPaley

### Что сделано
1. Написана программа в `Julia`

2021-04-06 17:37 UTC, MarinaPaley commented on Work-1/Task 1-2.jl
> +
[Nit:](https://google.github.io/eng-practices/review/reviewer/standard.html) стоит убрать лишние пробелы

2021-04-06 17:37 UTC, MarinaPaley commented on Work-1/Task 1-2.jl
> +#rad_str = input("Угол = ");
[Nit:](https://google.github.io/eng-practices/review/reviewer/standard.html) обычно стараются избегать закомментированных строк кода, либо исправляя их, либо удаляя.

2021-04-06 18:06 UTC, Const-Phi requested changes
Стоит добавить "отбивки" в виде пустых строк для того, чтобы повысить читаемость исходного кода, а то файл выглядит как каша.

2021-04-06 18:06 UTC, Const-Phi commented on Work-1/Task 1-2.jl
> +end;
[**NIT:**](https://google.github.io/eng-practices/review/reviewer/standard.html#:~:text=Reviewers%20should%20always%20feel%20free,they%20could%20choose%20to%20ignore.) я бы добавил сюда пустую строку для улучшения читаемости

2021-05-18 18:24 UTC, MarinaPaley commented
Проверено, есть замечания по наименованию переменных. Оставим так

2021-05-18 18:24 UTC, merged